config/routes.rb
Rails.application.routes.draw do
  resources :places
  devise_for :users, controllers: { registrations: 'registrations'}
 

  root 'pages#home'

end

app/models/place.rb
class Place < ActiveRecord::Base

	validates_presence_of :name 
	validates_presence_of :type
	validates_presence_of :address 
	validates_presence_of :start
	validates_presence_of :end
	validates_presence_of :user_id 

	belongs_to :user

	geocoded_by :address 
	after_validation :geocode 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
   has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy ]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @places = Place.all
    respond_with(@places)
  end

  def show
    respond_with(@place)
  end

  def new
    @place = Place.new
    respond_with(@place)
  end

  def edit
  end

  def create
    @place = current_user.places.new(place_params)
    @place.save
    respond_with(@place)
  end

  def update
    @place.update(place_params)
    respond_with(@place)
  end

  def destroy
    @place.destroy
    respond_with(@place)
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name, :type, :host, :start, :end, :address, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

		def sign_up_params
		params.require(:user).permit(:name, :email, :password)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :current_password)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "EventU", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><%= link_to 'Events', places_path %></li>
        
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
          <li><%= link_to 'Settings', edit_user_registration_path %> </li>          
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Signup', new_user_registration_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<% flash.each do |type, message|  %>
	<div class="alert alert-info fade-in">
		<button class="close" data-dismiss="alert">x</button>
		<%= message %>
	</div>
<% end %>

<% if current_page?(root_path) %>
	<div class="landing">
<% else %>
	<div class="container">
<% end %>

	<%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="text-center landing_title">
	<%= link_to "Find events you'll fall in love with!", places_path, class: 'btn btn-default btn-lg btn-landing' %>
</div>

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :type, required: true %>
    <%= f.input :host, required: true %>
    <%= f.input :start, required: true %>
    <%= f.input :end, required: true %>
    <%= f.input :address, required: true %>
    <%= f.input :description, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing Events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Host</th>
      <th>Start</th>
      <th>End</th>
      <th>User</th>
      <th>Address</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.type %></td>
        <td><%= place.host %></td>
        <td><%= place.start %></td>
        <td><%= place.end %></td>
        <td><%= place.user_id %></td>
        <td><%= place.address %></td>
        <td><%= place.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %> 
  <%= link_to 'New Place', new_place_path %>
<% end %>

app/views/places/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @place.type %>
</p>

<p>
  <strong>Host:</strong>
  <%= @place.host %>
</p>

<p>
  <strong>Start:</strong>
  <%= @place.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @place.end %>
</p>

<p>
  <strong>User:</strong>
  <%= @place.user_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <%= @place.longitude %>
  <%= @place.latitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>